301 Moved to Javascript Folder
codefellows/data-structures-and-algorithms pull request #30
Opened 2021-03-09 21:29 UTC by johncokos

2021-03-23 20:29 UTC, brookr commented
@johncokos Is the script to download the challenges still delivering them to the correct path?

2021-04-06 20:22 UTC, brookr commented
Also has conflicts

2021-04-13 20:14 UTC, brookr commented
@johncokos Resolve merge conflicts, please, and complete testing.

2021-04-14 18:37 UTC, johncokos commented
Conflicts cleared, code updated. Let's go!

2021-04-27 20:27 UTC, brookr commented
I don't like naming the folders based on the course codes, makes it look more like school work, rather than a portfolio building repo. Can we combine the js challenges into a single folder?

2021-05-04 20:07 UTC, brookr requested changes
Thanks, @johncokos !

2021-05-04 20:07 UTC, brookr commented on README.md
> +Under the `javascript` repository, at the top level is a folder called `code-challenges`
wrong wording?

2021-05-04 20:07 UTC, brookr commented on javascript/301-code-challenges/bin/get-challenge.sh
> +`which curl` -s https://codefellows.github.io/code-301-guide/curriculum/class-$1/challenges/challenges-$1.test.js > ./301-code-challenges/challenges-$1.test.js
Remove `301`

2021-05-04 20:07 UTC, brookr commented on javascript/package.json
> +    "get-challenge": "`which bash` ./301-code-challenges/bin/get-challenge.sh",
remove `301`

2021-05-12 21:54 UTC, brookr commented
Ready to merge in the week of May 17th.

2021-05-19 17:55 UTC, merged